services:
  apisix:
    image: apache/apisix:3.9.1-debian
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    ports:
      - "9080:9080"
      - "9180:9180"
    depends_on:
      - etcd
    restart: on-failure
  etcd:
    image: bitnami/etcd:3.5.15
    environment:
      ETCD_ENABLE_V2: true
      ALLOW_NONE_AUTHENTICATION: yes
      ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2397
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2397
  apisix-dashboard:
    image: apache/apisix-dashboard:2.13-alpine
    volumes:
      - ./dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
      - "9000:9000"
    depends_on:
      - apisix
  prometheus:
    image: prom/prometheus:v2.53.1
    volumes:
      - ./prometheus_conf/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - apisix
  grafana:
    image: grafana/grafana:11.1.1
    volumes:
      - ./grafana_conf/provisioning:/etc/grafana/provisioning
      - ./grafana_conf/dashboards:/var/lib/grafana/dashboards
      - ./grafana_conf/config/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
  oldapi:
    build: old-api
    ports:
      - "8081:8081"
  newapi:
    build: new-api
    ports:
      - "8082:8082"
    networks:
      default:
        aliases:
          - new.api
