apisix:
  extra_lua_path: /opt/?.lua
nginx_config:
  http:
    custom_lua_shared_dict:
      plugin-unauth-limit: 100m
deployment:
  admin:
    allow_admin:
      - 0.0.0.0/0
  etcd:
    host:
      - http://etcd:2397
plugins:
  - key-auth                       # priority: 2500
  - proxy-mirror                   # priority: 1010
  - proxy-rewrite                  # priority: 1008
  - traffic-split                  # priority: 966
  - redirect                       # priority: 900
  - response-rewrite               # priority: 899
  - prometheus                     # priority: 500
  - unauth-limit                   # priority: 100
plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091
