deployment:
  admin:
    admin_key:
      - name: admin
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin
    allow_admin:
      - 0.0.0.0/0
  etcd:
    host:
      - http://etcd:2397
plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091
